config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login'
  get 'sessions/home'
  get 'sessions/profile'
  get 'sessions/setting'
  post 'sessions/login_attempt'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end

  resources :users
  # match ':controller(/:action(/:id))(.:format)'
  root 'posts#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments , dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true , length: {minimum: 10}
end

app/models/user.rb
require 'digest/sha1'

class User < ApplicationRecord
  EMAIL_REGEX = /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, format: { with: EMAIL_REGEX }
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  def encrypt_password
    if password.present?
      self.salt = Digest::SHA1.hexdigest(" We add #{email} as unique value and #{Time.now} as random value")
      self.password=  Digest::SHA1.hexdigest("Adding #{salt} to {password}")
    end
  end


  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end
  def match_password(login_password="")
    password == Digest::SHA1.hexdigest("Adding #{salt} to {password}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id]
      return true
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      return false
    end
  end
  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, :except => [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    puts "show method"
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_url
  end


  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def login_attempt
    authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.username}"
      redirect_to(:action => 'home')
    else
      flash[:notice] = "Invalid Username or Password"
      flash[:color]= "invalid"
      render "login"
    end
  end

  def home
  end

  def profile
  end

  def setting
  end

  def logout
    session[:user_id] = nil
    redirect_to :action => 'login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    render "new"
  end
  def user_params
    params.require(:user).permit(:username, :email, :password, :salt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="container-fluid row">
  <div class="col">
    <p>Name: <strong><%= comment.name %></strong></p>
    <div class="row">
      <div class="col">
        <p>Body: <%= comment.body %></p>
      </div>
      <div class="col-9" style="color: blue">
        <p><%= time_ago_in_words(comment.created_at) %> Ago</p>
      </div>
    </div>

  </div>
  <div class="col">
      <%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "btn btn-light",
                  data: {confirm: "Are You Sure"}
      %>
  </div>
</div>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="form-group row">
    <%= f.label :name, :class =>"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name , :class => "form-control" , :placeholder => "Name"%>
    </div>
  </div>


  <div class="form-group row">
    <%= f.label :body, :class =>"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_area :body , :class => "form-control" , :placeholder => "Post Body"%>
      <br>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @post.errors[:body].each do |msg| %>
              <li class="p-3 mb-2 bg-danger text-white">Body <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <%= f.submit :class => "btn btn-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ROR Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/posts/new">New Post</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <% if session[:user_id] == nil %>
          <a class="nav-link" href="/sessions/login" >Sign In</a>
          <a class="nav-link" href="/users/new" >Sign Up</a>
          <%end %>
          <% if session[:user_id] != nil %>
          <a class="nav-link" href="#" >Log Out</a>
            <%end %>
        </div>
      </div>
    </nav>
  </head>

  <body>
  <div class="container-fluid">

  <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group row">
    <%= f.label :title, :class =>"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_field :title , :class => "form-control" , :placeholder => "Title"%>
      <% if @post.errors.any? %>
        <br>
        <div id="error_explanation">
          <ul>
            <% @post.errors[:title].each do |msg| %>
              <li class="p-3 mb-2 bg-danger text-white">Title <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>


  <div class="form-group row">
    <%= f.label :body, :class =>"col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_area :body , :class => "form-control" , :placeholder => "Post Body"%>
      <br>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @post.errors[:body].each do |msg| %>
              <li class="p-3 mb-2 bg-danger text-white">Body <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title">
      <%= link_to post.title, post %>
    </h2>
    <p class="date">
      <%= post.created_at.strftime("%B, %d, %Y") %>
    </p>
  </div>
  <hr>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="title">
  <%= @post.title %>
</h1>

<p class="date">
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  |<%= link_to 'Edit', edit_post_path(@post) %>
  |<%= link_to 'Destroy', post_path(@post), method: :delete, data: {confirm: 'Are You Sure'} %>
</p>

<h3 class="body">
  <%= @post.body %>
</h3>
<hr>
<div>
  <h4 style="color: blue">
    <%= @post.comments.count %> Comments
  </h4>
  <%= render @post.comments %>
  <h3>Add a Comment:</h3>
  <%= render "comments/form" %>
</div>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
      <% @user.errors.full_messages.each {|message_error| %>
      <li>* <%=  message_error  %></li>
      <%  } %>
    </ul>
  <% end %>
</div>